site_name: Audit & Accountability Policy
docs_dir: docs

# ─── MARKDOWN EXTENSIONS ─────────────────────────────────────────────────────
# The built-in `toc` extension adds IDs and permalinks to your headers.
markdown_extensions:
  - toc:
      permalink: true

# ─── THEME ──────────────────────────────────────────────────────────────────
theme:
  name: material

# ─── NAVIGATION ─────────────────────────────────────────────────────────────
nav:
  - Home: index.md
  - Purpose: purpose.md
  - Scope: scope.md
  - Roles & Responsibilities: roles.md
  - Review Cycle: review_cycle.md
