site_name: Audit & Accountability Policy
docs_dir: docs

# ─── PLUGINS ────────────────────────────────────────────────────────────────
plugins:
  - search # enable the built-in MkDocs search box
  - toc: # table-of-contents plugin
      permalink: true # add a ¶ link to each heading

# ─── THEME ──────────────────────────────────────────────────────────────────
theme:
  name: material

# ─── NAVIGATION ─────────────────────────────────────────────────────────────
nav:
  - Home: index.md
  - Purpose: purpose.md
  - Scope: scope.md
  - Roles & Responsibilities: roles.md
  - Review Cycle: review_cycle.md
