name: Build & Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write    # allow checkout + committing back
  pages: write       # allow Pages deployment
  id-token: write    # (not strictly needed for peaceiris but harmless)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install MkDocs & theme
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # 4) Build the static site into ./site
      - run: mkdocs build --site-dir site

      # 5) Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

