name: Incident-Driven Alerts

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  alert:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
        env:
          discovery.type: single-node
          xpack.security.enabled: 'false'
        # ports mapping isn’t strictly needed for service containers,
        # but it makes localhost:9200 available
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -s http://localhost:9200"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install elasticsearch requests

      - name: Wait for Elasticsearch
        run: |
          echo "Waiting for Elasticsearch to be available…"
          until curl -s http://localhost:9200 >/dev/null; do sleep 1; done

      - name: Run unauthorized-access checker
        env:
          ES_URL:       http://localhost:9200
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUB_REPO:  snarls94/analytics-prep
          SITE_URL:     https://snarls94.github.io/analytics-prep/
          LOOKBACK_MIN: 5
        run: python scripts/check_unauth_alert.py

