name: Incident-Driven Alerts

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  alert:
    runs-on: [ self-hosted, macOS ]

    steps:
      - uses: actions/checkout@v3

      - name: Create Python virtual environment
        run: python3 -m venv .venv_alert

      - name: Install dependencies
        run: |
          source .venv_alert/bin/activate
          pip install --upgrade pip
          pip install elasticsearch requests

      - name: Run unauthorized-access checker
        env:
          ES_URL:       http://localhost:9200
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUB_REPO:  snarls94/analytics-prep
          SITE_URL:     https://snarls94.github.io/analytics-prep/
          LOOKBACK_MIN: 5
        run: |
          source .venv_alert/bin/activate
          python scripts/check_unauth_alert.py
