name: Incident-Driven Alerts

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  alert:
    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # use the system python that comes with macOS
          pip3 install --user elasticsearch requests

      - name: Run unauthorized-access checker
        env:
          ES_URL: http://localhost:9200
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUB_REPO: snarls94/analytics-prep
          SITE_URL: https://snarls94.github.io/analytics-prep/
          LOOKBACK_MIN: 5
        run: python3 scripts/check_unauth_alert.py
