name: Schedule Annual Policy Review

on:
  schedule:
    - cron: '0 14 1 1 *'  # January 1 at 14:00 UTC (10 AM EST)

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Create Policy Review Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Annual Policy Review",
              body: `It’s time to review our Audit & Accountability Policy docs:

- Live site: https://snarls94.github.io/analytics-prep/
- Checklist:
  1. Verify Roles & Responsibilities
  2. Confirm retention schedules
  3. Update after any security incident

_Assign yourself and close when complete._`
